include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    always_put_required_named_parameters_first: true
    avoid_classes_with_only_static_members: false
    sort_constructors_first: true
    prefer_single_quotes: true
    public_member_api_docs: false
    always_specify_types: false
    lines_longer_than_80_chars: true
    omit_local_variable_types: false

analyzer:
  errors:
    invalid_uri: error
  exclude:
    - lib/**/*.g.dart
    - lib/*.g.dart
    - lib/**/*.freezed.dart
    - lib/common/ui/pop_peek/**/*
    - test/_data/**